spring:
  application:
    name: eurekaClient
  cloud:
    config:
      server:
        git:
          uri: https://github.com/richard889/MeetingConfig
          username: richard889
          password: jack0816      